name: Call Central AI Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    
permissions:           
  contents: read
  pull-requests: write

jobs:
  ai-review:
    uses: SatishBhusarapudev/.github/.github/workflows/ai-review.yml@main
    secrets: inherit
